version: 1.2
workflows:
  - name: test
    subclass: WDL
    primaryDescriptorPath: /test.wdl
  - name: countNs
    subclass: WDL
    primaryDescriptorPath: /countNs.wdl
  - name: countNs_parallel
    subclass: WDL
    primaryDescriptorPath: /countNs.parallel.wdl
